//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoai.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDetail
    {
        public int PayDetailID { get; set; }
        public int PayID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Describe { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Pay Pay { get; set; }
        public virtual Product Product { get; set; }
    }
}
