//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoai.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillSaleDetail
    {
        public int BillDetailID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> PriceProduct { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PromotionID { get; set; }
    
        public virtual BillOfSale BillOfSale { get; set; }
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
