//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoai.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public Nullable<int> OrderInvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> PriceProduct { get; set; }
    
        public virtual OrderInvoice OrderInvoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
